# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OS_search_for_addresses
                                 A QGIS plugin
 Search for addresses if you have an OS API Key
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-02-04
        copyright            : (C) 2021 by Paul Withington
        email                : pwithy@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load OS_search_for_addresses class from file OS_search_for_addresses.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .addresssearch import OS_search_for_addresses
    return OS_search_for_addresses(iface)
